changelog:
  categories:
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Breaking Changes
      labels:
        - semver:major
    - title: Infrastructure
      labels:
        - chore
        - ci
    - title: Other Changes
      labels:
        - "*"
