"""Markdown renderer for post-hoc panel reporting.

Pure renderer: consumes an :class:`InspectReport` plus the raw panel JSON
dict and returns a complete Markdown document. No I/O, no mutation of the
input. The caller is responsible for writing the returned string to stdout
or disk.

Section order and the mandatory synthetic-panel banner/footer strings are
fixed by spec (see ``specs/sp-viz-layer/structure.md`` §2 and §7) and are
enforced by tests.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from synth_panel.analysis.inspect import InspectReport


BANNER = (
    "> **Synthetic panel.** All responses below were generated by AI personas,\n"
    "> not human respondents. Do not cite as user-research data."
)

FOOTER = "_Generated by synthpanel report. Synthetic panel — AI-generated responses, not human data._"


def render_markdown(
    report: InspectReport,
    raw: dict[str, Any],
    *,
    source_path: str | None = None,
) -> str:
    """Render a complete Markdown report for a saved panel result.

    Pure function. Sections are emitted in the order defined by
    structure.md §2; the banner and footer are hard-coded and verbatim.
    """

    parts: list[str] = []

    title_id = report.result_id or "(unsaved result)"
    parts.append(f"# Panel Report: {title_id}")
    parts.append("")
    parts.append(BANNER)
    parts.append("")

    parts.extend(_provenance_block(report, raw, source_path=source_path))
    parts.append("")

    parts.extend(_overview_block(report))
    parts.append("")

    parts.extend(_model_rollup_block(report))
    parts.append("")

    parts.extend(_persona_summary_block(report))
    parts.append("")

    parts.extend(_synthesis_block(report))
    parts.append("")

    parts.extend(_failure_stats_block(report))

    if report.warnings:
        parts.append("")
        parts.extend(_warnings_block(report))

    parts.append("")
    parts.append(FOOTER)

    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------


def _provenance_block(
    report: InspectReport,
    raw: dict[str, Any],
    *,
    source_path: str | None,
) -> list[str]:
    """Section 3 — provenance table per structure.md §7.

    Missing fields degrade to ``(not recorded)`` / ``(unknown)`` rather
    than raising ``KeyError``. Rows for optional fields (``total_seconds``,
    ``synthesis_model``) are omitted when the source data is absent.
    """
    metadata = raw.get("metadata") if isinstance(raw.get("metadata"), dict) else {}
    version = metadata.get("version") if isinstance(metadata.get("version"), dict) else {}
    cost_meta = metadata.get("cost") if isinstance(metadata.get("cost"), dict) else {}
    timing = metadata.get("timing") if isinstance(metadata.get("timing"), dict) else {}
    models_meta = metadata.get("models") if isinstance(metadata.get("models"), dict) else {}

    config_hash = metadata.get("config_hash")
    synthpanel_version = version.get("synthpanel")
    python_version = version.get("python")
    pricing_snapshot_date = cost_meta.get("pricing_snapshot_date")
    created_at = raw.get("created_at") or report.created_at
    total_seconds = timing.get("total_seconds")

    panelist_models_meta = models_meta.get("panelist")
    if isinstance(panelist_models_meta, list) and panelist_models_meta:
        panelist_models_str = ", ".join(str(m) for m in panelist_models_meta)
    elif report.models:
        panelist_models_str = ", ".join(report.models)
    elif report.model:
        panelist_models_str = report.model
    else:
        panelist_models_str = "(unknown)"

    synthesis_model = models_meta.get("synthesis") or report.synthesis.model

    rows: list[tuple[str, str]] = [
        ("config_hash", _fmt(config_hash, missing="(not recorded)")),
        ("synthpanel_version", _fmt(synthpanel_version)),
        ("python_version", _fmt(python_version)),
        ("pricing_snapshot_date", _fmt(pricing_snapshot_date)),
        ("created_at", _fmt(created_at)),
    ]
    if total_seconds is not None:
        rows.append(("total_seconds", f"{total_seconds}"))
    rows.append(
        (
            "source_path",
            source_path if source_path else "(loaded by ID)",
        )
    )
    rows.append(("panelist_model(s)", panelist_models_str))
    if synthesis_model:
        rows.append(("synthesis_model", str(synthesis_model)))

    lines: list[str] = ["## Provenance", ""]
    lines.extend(_md_table(["Field", "Value"], rows))
    return lines


def _overview_block(report: InspectReport) -> list[str]:
    """Section 4 — overview counts + path + cost header.

    The cost row uses ``report.total_cost`` as the pre-formatted
    ``$0.0000`` string produced upstream by ``format_summary()`` (design
    §Rationale, seam 2) — no float re-formatting.
    """
    lines: list[str] = ["## Overview", ""]
    rows: list[tuple[str, str]] = [
        ("Personas", str(report.persona_count)),
        ("Questions", str(report.question_count)),
        ("Rounds", _rounds_cell(report)),
        ("Total tokens", str(report.total_tokens)),
    ]
    if report.total_cost:
        rows.append(("Total cost", report.total_cost))
    if report.panelist_cost:
        rows.append(("Panelist cost", report.panelist_cost))
    if report.instrument_name:
        rows.append(("Instrument", report.instrument_name))
    if report.extraction_present:
        rows.append(("Extraction", "present (post-hoc structured extraction used)"))
    if not report.has_rounds_shape:
        rows.append(("Shape", "flat (saved via --save; no rounds metadata)"))

    lines.extend(_md_table(["Field", "Value"], rows))

    if report.path:
        lines.append("")
        lines.append(f"**Path:** {' → '.join(_escape_md(p) for p in report.path)}")
    return lines


def _model_rollup_block(report: InspectReport) -> list[str]:
    """Section 5 — per-model rollup table."""
    lines: list[str] = ["## Per-Model Rollup", ""]
    if not report.model_rollup:
        lines.append("_No model usage recorded._")
        return lines
    headers = ["Model", "Personas", "Answered", "Input", "Output", "Total", "Cost"]
    rows: list[tuple[str, ...]] = []
    for m in report.model_rollup:
        cost = f"${m.cost_usd:.4f}" if m.cost_usd is not None else "—"
        rows.append(
            (
                m.model,
                str(m.personas),
                str(m.questions_answered),
                str(m.input_tokens),
                str(m.output_tokens),
                str(m.total_tokens),
                cost,
            )
        )
    lines.extend(_md_table(headers, rows))
    return lines


def _persona_summary_block(report: InspectReport) -> list[str]:
    """Section 6 — per-persona summary table."""
    lines: list[str] = ["## Per-Persona Summary", ""]
    if not report.personas:
        lines.append("_No panelists recorded._")
        return lines
    headers = ["Persona", "Model", "Responses", "Errors", "Notes"]
    rows: list[tuple[str, ...]] = []
    for p in report.personas:
        rows.append(
            (
                p.name,
                p.model or "(unknown)",
                str(p.response_count),
                str(p.error_count),
                p.panelist_error or "",
            )
        )
    lines.extend(_md_table(headers, rows))
    return lines


def _synthesis_block(report: InspectReport) -> list[str]:
    """Section 7 — synthesis status, themes, summary peek."""
    lines: list[str] = ["## Synthesis", ""]
    s = report.synthesis
    if not s.ran and s.error is None and s.summary_peek is None:
        lines.append("_Not run._")
        return lines
    if s.error and not s.ran:
        lines.append(f"**Status:** failed — {_escape_inline(s.error)}")
        return lines
    lines.append("**Status:** ran")
    meta_rows: list[tuple[str, str]] = []
    if s.model:
        meta_rows.append(("Model", str(s.model)))
    if s.cost:
        meta_rows.append(("Cost", str(s.cost)))
    if s.theme_count:
        meta_rows.append(("Themes", str(s.theme_count)))
    if meta_rows:
        lines.append("")
        lines.extend(_md_table(["Field", "Value"], meta_rows))
    if s.summary_peek:
        lines.append("")
        lines.append("**Summary peek:**")
        lines.append("")
        lines.append("> " + s.summary_peek.replace("\n", "\n> "))
    return lines


def _failure_stats_block(report: InspectReport) -> list[str]:
    """Section 8 — failure stats."""
    fs = report.failure_stats
    lines: list[str] = ["## Failure Stats", ""]
    rows: list[tuple[str, str]] = [
        ("Total pairs", str(fs.total_pairs)),
        ("Errored pairs", str(fs.errored_pairs)),
        ("Failure rate", f"{fs.failure_rate:.1%}"),
    ]
    if fs.failed_panelists:
        rows.append(("Failed panelists", str(fs.failed_panelists)))
    if fs.errored_personas:
        shown = ", ".join(_escape_md(n) for n in fs.errored_personas[:6])
        extra = len(fs.errored_personas) - 6
        if extra > 0:
            shown += f", +{extra} more"
        rows.append(("Affected personas", shown))
    lines.extend(_md_table(["Field", "Value"], rows))
    return lines


def _warnings_block(report: InspectReport) -> list[str]:
    """Section 9 — warnings (only rendered when present)."""
    lines: list[str] = ["## Warnings", ""]
    for w in report.warnings:
        lines.append(f"- {_escape_inline(w)}")
    return lines


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _banner() -> str:
    """Return the mandatory synthetic-panel banner verbatim."""
    return BANNER


def _md_table(headers: list[str], rows: list[tuple[str, ...]] | list[tuple[str, str]]) -> list[str]:
    """Render a GitHub-Flavored Markdown table. Cell values are escaped."""
    out: list[str] = []
    out.append("| " + " | ".join(_escape_md(h) for h in headers) + " |")
    out.append("| " + " | ".join(["---"] * len(headers)) + " |")
    for row in rows:
        out.append("| " + " | ".join(_escape_md(c) for c in row) + " |")
    return out


def _escape_md(value: Any) -> str:
    """Escape pipe, backtick, and angle brackets for safe cell rendering.

    Also replaces newlines with a space so a stray LF doesn't break the
    single-line table row layout.
    """
    s = "" if value is None else str(value)
    s = s.replace("\\", "\\\\")
    s = s.replace("|", "\\|")
    s = s.replace("`", "\\`")
    s = s.replace("<", "&lt;")
    s = s.replace(">", "&gt;")
    s = s.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")
    return s


def _escape_inline(value: Any) -> str:
    """Escape angle brackets + backticks for inline (non-table) text."""
    s = "" if value is None else str(value)
    s = s.replace("<", "&lt;").replace(">", "&gt;")
    return s


def _fmt(value: Any, *, missing: str = "(unknown)") -> str:
    """Format a provenance value, falling back to ``missing`` when empty."""
    if value is None or value == "":
        return missing
    return str(value)


def _rounds_cell(report: InspectReport) -> str:
    if not report.round_names:
        return "0"
    return f"{len(report.round_names)} ({', '.join(report.round_names)})"
